[package]
name = "crypto-core"
version = "0.1.0"
edition = "2024"

[dependencies]
oqs = "0.11.0"  
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.21"
anyhow = "1.0"
eframe = "0.22"
rfd = "0.13"